name: coa
task_prefix: "Plan: "
task_file: data/coa/coa-query-1friendly-1enemy.joblib
max_steps: 7
num_fewshots: 0
eval_configs:
  k_folds: 2
  k_folds_seed: 42
ai_name: COA Planner

# Store extra YAML variables for supporting Llama3 models
llama_url: "localhost:11434"
react_llm_name: "command-r-plus:104b-fp16"
stream: True
