name: expel
llm: gpt-4o-mini
max_reflection_depth: 3
max_num_rules: 20
truncate_strategy: null
fewshot_strategy: task_similarity # task_similarity, step_similarity, reflection_similarity, thought_similarity, action_similarity, rotation, task_thought_similarity
critique_truncate_strategy: random
success_critique_num: 8
retrieval_kwargs:
  embedder_path: "all-mpnet-base-v2" # sentence-transformers/all-mpnet-base-v2
  embedder_type: huggingface
  retriever_type: knn # knn or svm
  buffer_retrieve_ratio: 4
  reranker: none
  max_fewshot_tokens: auto